In [4]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [3]:
orders=pd.read_csv('C:\\Users\\vedss\\Downloads\\orders.csv')
users=pd.read_json('C:\\Users\\vedss\\Downloads\\users.json')
users.head()

   user_id    name       city membership
0        1  User_1    Chennai    Regular
1        2  User_2       Pune       Gold
2        3  User_3  Bangalore       Gold
3        4  User_4  Bangalore    Regular
4        5  User_5       Pune       Gold

In [5]:
engine=create_engine("mysql+pymysql://root:admin@localhost/techeval")

In [6]:
restaurants=pd.read_sql('restaurants',engine)

In [ ]:
ordersusers=pd.merge(orders,users,how='left',on='user_id')
final=pd.merge(ordersusers,restaurants,how='left',on='restaurant_id')
final.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name_x,name,city,membership,restaurant_name_y,cuisine,rating
0,1,2508,450,18-02-2023,842.97,New Foods Chinese,User_2508,Hyderabad,Regular,Restaurant_450,Mexican,3.2
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine,User_2693,Pune,Regular,Restaurant_309,Indian,4.5
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi,User_2084,Chennai,Gold,Restaurant_107,Mexican,4.0
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg,User_319,Bangalore,Gold,Restaurant_224,Chinese,4.8
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian,User_1064,Pune,Regular,Restaurant_293,Italian,3.0

In [71]:
final.to_csv('final_food_delivery_dataset.csv')

In [54]:
goldcityrevenue=(
    final[final["membership"]=="Gold"]
    .groupby("city")["total_amount"]
    .sum()
    .reset_index(name="totalrevenue")
    .sort_values("totalrevenue",ascending=False)
)
#highest total revenue cities from gold members
print(goldcityrevenue)

        city  totalrevenue
1    Chennai    1080909.79
3       Pune    1003012.32
0  Bangalore     994702.59
2  Hyderabad     896740.19

In [55]:
avgcuisine=(
    final.groupby("cuisine")["total_amount"]
    .mean()
    .reset_index(name="avgorder")
    .sort_values("avgorder",ascending=False)
)
print(avgcuisine)
#average order value by cuisine

   cuisine    avgorder
3  Mexican  808.021344
2  Italian  799.448578
1   Indian  798.466011
0  Chinese  798.389020

In [56]:
userspend=(
    final.groupby("user_id")["total_amount"]
    .sum()
    .reset_index(name="total_amount")
)
user_count=userspend[userspend["total_amount"]>1000]["user_id"].nunique()
print(user_count)
#number of users who have spent more than $1000

2544

In [57]:
def ratingbucket(r):
    if 3<=r<3.5:
        return "3 to 3.5"
    elif 3.6<=r<4:
        return "3.6 to 4"
    elif 4.1<=r<4.5:
        return "4.1 to 4.5"
    elif 4.6<=r<5:
        return "4.6 to 5"
    else:
        return "<3 & >5"

final["ratingrange"]=final["rating"].apply(ratingbucket)

ratingrevenue=(
    final.groupby("ratingrange")["total_amount"]
    .sum()
    .reset_index(name="totalrevenue")
    .sort_values("totalrevenue",ascending=False)
)
print(ratingrevenue)
#total revenue by restaurant rating range

  ratingrange  totalrevenue
3    4.6 to 5    2037344.28
0    3 to 3.5    1817950.65
2  4.1 to 4.5    1481279.23
1    3.6 to 4    1399232.99
4     <3 & >5    1275816.97

In [58]:
goldcityavg=(
    final[final["membership"]=="Gold"]
    .groupby("city")["total_amount"]
    .mean()
    .reset_index(name="avgordervalue")
    .sort_values("avgordervalue",ascending=False)
)
print(goldcityavg)
#average order value by city for gold members

        city  avgordervalue
1    Chennai     808.459080
2  Hyderabad     806.421034
0  Bangalore     793.223756
3       Pune     781.162243

In [59]:
cuisinestats=(
    final.groupby("cuisine")
    .agg(restaurantcount=("restaurant_id","nunique"),totalrevenue=("total_amount","sum"))
    .sort_values(["restaurantcount","totalrevenue"], ascending=[True,False])
)
print(cuisinestats)
#cuisine with least number of restaurants but highest total revenue

         restaurantcount  totalrevenue
cuisine
Chinese              120    1930504.65
Italian              126    2024203.80
Indian               126    1971412.58
Mexican              128    2085503.09

In [61]:
goldorderpercentage=round((final["membership"].eq("Gold").sum()*100)/len(final))
print(goldorderpercentage)
#percentage of orders from gold members

50

In [62]:
restaurants=[
    "Grand Cafe Punjabi",
    "Grand Restaurant South Indian",
    "Ruchi Mess Multicuisine",
    "Ruchi Foods Chinese"
]
restaurantaov=(
    final[final["restaurant_name_x"].isin(restaurants)]
    .groupby(["restaurant_id","restaurant_name_x"])
    .agg(avgordervalue=("total_amount","mean"),totalorders=("order_id","count"))
    .reset_index()
)
restaurantaov=(restaurantaov[restaurantaov["totalorders"]<20]
.sort_values("avgordervalue",ascending=False)
)
print(restaurantaov)
#average order value for restaurants with less than 20 orders

   restaurant_id        restaurant_name_x  avgordervalue  totalorders
3            385  Ruchi Mess Multicuisine     938.202778           18
1            116       Grand Cafe Punjabi     775.850000           12
5            421      Ruchi Foods Chinese     686.603158           19

In [63]:
combinations=final[
    ((final["membership"]=="Gold")&(final["cuisine"]=="Indian"))|
    ((final["membership"]=="Gold")&(final["cuisine"]=="Italian"))|
    ((final["membership"]=="Regular")&(final["cuisine"]=="Indian"))|
    ((final["membership"]=="Regular")&(final["cuisine"]=="Chinese"))
]

combinationsrevenue=(
    combinations
    .groupby(["membership","cuisine"])["total_amount"]
    .sum()
    .reset_index(name="totalrevenue")
    .sort_values("totalrevenue",ascending=False)
)
print(combinationsrevenue)
#total revenue for combinations

  membership  cuisine  totalrevenue
1       Gold  Italian    1005779.05
3    Regular   Indian     992100.27
0       Gold   Indian     979312.31
2    Regular  Chinese     952790.91

In [ ]:
final.dtypes #Checking data type for order_date

order_id               int64
user_id                int64
restaurant_id          int64
order_date            object
total_amount         float64
restaurant_name_x     object
name                  object
city                  object
membership            object
restaurant_name_y     object
cuisine               object
rating               float64
ratingrange           object
dtype: object

In [64]:
df=final.copy()

df["order_date"]=pd.to_datetime(df["order_date"],format="%d-%m-%Y")

df["quarter"]=df["order_date"].dt.month.map(
    lambda m:
        "Q1 (Jan–Mar)" if m<=3 else
        "Q2 (Apr–Jun)" if m<=6 else
        "Q3 (Jul–Sep)" if m<=9 else
        "Q4 (Oct–Dec)"
)

quarterrevenue=(
    df.groupby("quarter")["total_amount"]
    .sum()
    .reset_index(name="totalrevenue")
    .sort_values("totalrevenue",ascending=False)
)

print(quarterrevenue)
#revenue split into quarters

        quarter  totalrevenue
2  Q3 (Jul–Sep)    2037385.10
3  Q4 (Oct–Dec)    2018263.66
0  Q1 (Jan–Mar)    2010626.64
1  Q2 (Apr–Jun)    1945348.72

In [65]:
goldorders=final[final["membership"]=="Gold"]["order_id"].count()
print(goldorders)
#number of orders from gold members

4987

In [66]:
revenuehyderabad=round(final[final["city"]=="Hyderabad"]["total_amount"].sum())
print(revenuehyderabad)
#total revenue from Hyderabad

1889367

In [67]:
distinctusersorders=df["user_id"].nunique()
#no need for any extra commands for atleast one order since data is stored according to orders
print(distinctusersorders)
#number of distinct users who have placed orders

2883

In [68]:
avgordergold=round(final[final["membership"]=="Gold"]["total_amount"].mean(), 2)
print(avgordergold)
#average order value for gold members

797.15

In [69]:
orders=final[final["rating"]>=4.5]["order_id"].count()
print(orders)
#number of orders from restaurants with rating 4.5 and above

3374

In [70]:
topcity=(final[final["membership"]=="Gold"].groupby("city")["total_amount"].sum().idxmax())
#city with highest total revenue from gold members
orderstopcitygold=final[(final["membership"]=="Gold")&(final["city"]==topcity)]["order_id"].count()
print(orderstopcitygold)
#number of orders from gold members in the city with highest total revenue from gold members

1337

In [72]:
len(final)

10000